# Generated by Django 3.2.15 on 2022-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.BigIntegerField(choices=[(0, 'Admin'), (1, 'Customer')], default=1, max_length=2),
        ),
    ]
