# Generated by Django 3.2.15 on 2022-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.BigIntegerField(choices=[(0, 'Admin'), (1, 'Customer')], default=1, editable=False, max_length=2),
        ),
    ]
