# Generated by Django 3.2.15 on 2022-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_sach',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='id_category',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
